import keymirror from 'keymirror';

export default keymirror({
  loginFail: null,
  loginSuccess: null,
  fetchHomePageSuccess: null,
  fetchHomePageFail: null,
  fetchStoriesSuccess: null,
  fetchStoriesFail: null,
  fetchStorySuccess: null,
  fetchStoryFail: null,
  fetchPhotosSuccess: null,
  fetchPhotosFail: null,
  clapStorySuccess: null,
  clapStoryFail: null,
  unclapStorySuccess: null,
  unclapStoryFail: null,
  likePhotosSuccess: null,
  likePhotosFail: null,
  dislikePhotosSuccess: null,
  dislikePhotosFail: null,
  likePhotoSuccess: null,
  likePhotoFail: null,
  dislikePhotoSuccess: null,
  dislikePhotoFail: null,
  addCommentSuccess: null,
  addCommentFail: null,
  editCommentSuccess: null,
  editCommentFail: null,
  deleteCommentSuccess: null,
  deleteCommentFail: null,
  fetchDraftsSuccess: null,
  fetchDraftsFail: null,
  fetchDraftSuccess: null,
  fetchDraftFail: null,
  fetchBookmarksSuccess: null,
  fetchBookmarksFail: null,
  fetchAboutSuccess: null,
  fetchAboutFail: null,
  fetchContactSuccess: null,
  fetchContactFail: null,
  fetchPhotoSuccess: null,
  fetchPhotoFail: null,
});
